### ISSUE TITLE
Скласти інтро.

### ISSUE THREAD

**Issue by YuliiaZviahina** [YuliiaZviahina/homepage#4]
Скласти інтро (вступ), де в 2-4 реченнях описати, що замовник робить, що подобається робити, що хочеться робити краще, що важливо робити, тощо.

**Comment by LidiaKach** [comment]
Вале́рий Я́ковлевич Лео́нтьев (род. 19 марта 1949, Усть-Уса, Коми АССР, СССР) — советский и российский певец, композитор и киноактёр; народный артист РФ (1996), заслуженный артист Украинской ССР (1987), лауреат премии Ленинского комсомола (1985).

**Comment by YuliiaZviahina** [comment]
Спасибо
